kind: Service
apiVersion: v1
metadata:
  name: apache-service
  namespace: apache-nm
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
    