apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counterapp-hpa
  namespace: nithin-nm
spec: 
  scaleTargetRef:
    kind: Deployment
    name: counterapp-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5  # This specifies that HPA will scale based on 5% average CPU utilization
